:concurrency: 5
:logfile: log/sidekiq.log
staging:
  :concurrency: 2
production:
  :concurrency: 3
:queues:
  - default

:schedule:
  station_worker:
    class: StationWorker
    every: ['3m', first_in: '0s']
    queue: default
    description: 'run Station.update_all_stations'
