:concurrency: 5
staging:
  :concurrency: 2
production:
  :concurrency: 2
:queues:
  - default

:schedule:
  StationWorker:
    class: StationWorker
    every: ['5m', first_in: '0s']
    queue: default
    description: 'Update stations db'
